netia1128/battleship

- lib/cell.rb
- spec/cell_spec.rb
- To create tests to check that a cell initializes correctly.
- Does the formatting look good?
> cell_initialize

- lib/cell.rb
- spec/cell_spec.rb
It adds tests and code for the cell.place_ship and cell.empty? methods.
No
> cell_place_ship

- lib/cell.rb
- spec/cell_spec.rb
Add #fired_upon? and #fire_upon methods and subsequent tests
> Cell fire upon

- lib/cell.rb
- spec/cell_spec.rb
Add cell.render method
Add cell.render tests
> cell_render

- lib/board.rb
- spec/board_spec.rb
Create board class
Create board tests
> Board initialize

- lib/board.rb
- spec/board_spec.rb
Refactor the board_validate work
> Refactor board validate

- lib/board.rb
- spec/board_spec.rb
Created #board.place tests
Created #board.place method
> Board place

- lib/board.rb
- lib/cell.rb
- spec/board_spec.rb
Add tests for #board_render
Add method for #board_render
Update #cell_render as needed
> Board render

- lib/board.rb
Refactor board class
- #valid_placement
- #render
- helper method names
> Board render refactor

- battleship_runner.rb
- lib/board.rb
- lib/board_generator.rb
> Board generator

- lib/board_generator.rb
- spec/board_generator_spec.rb
Add test for board_generator class
> Board generator tests

- battleship_runner.rb
- lib/game.rb
> Game main menu

- lib/board.rb
- lib/board_generator.rb
- lib/game.rb
- lib/player.rb
Purpose of pull request
Build out #player_information method in the Game class
> Game board creation

- battleship_runner.rb
- lib/board.rb
- lib/board_generator.rb
- lib/game.rb
- lib/player.rb
- spec/player_spec.rb
##Purpose of Pull Request:
Add test for Player #computron_placement
Add code for Player #computron_placement
> Computer placement

- lib/board.rb
- lib/game.rb
- lib/player.rb
Create #ship_placement_evaluation method
> Player placement

- lib/board.rb
- lib/game.rb
- lib/player.rb
- spec/board_spec.rb
Add tests for helper methods in board class
> Board spec helpers

- battleship_runner.rb
- lib/game.rb
- lib/player.rb
Add formatting for game play statements.
> Add formatting for game play statements

- lib/ship_generator.rb
- spec/ship_generator_spec.rb
#Purpose of PR
Create ShipGenerator class and tests
> Add tests and code for ship_generator class

- battleship_runner.rb
- lib/board.rb
- lib/board_generator.rb
- lib/evaluator.rb
- lib/game.rb
- lib/player.rb
- lib/ship_generator.rb
- spec/board_spec.rb
- spec/evaluator_spec.rb
- spec/player_spec.rb
- spec/ship_generator_spec.rb
> Smart shot

- battleship_runner.rb
- lib/cell.rb
- lib/game.rb
- lib/statement.rb
- spec/statement_spec.rb
Start to off load statement in game class into a statements class.
> Statement class
